Gtk.TeamFoundation.and.MonoDevelop.plugin.pre-alpha

diff --git a/trunk/configure b/trunk/configure
--- a/trunk/configure
+++ b/trunk/configure
@@ -1796,7 +1796,16 @@ fi
 
 
 # disable experimental stuff for now
-#PKG_CHECK_EXISTS(monodevelop, HAVE_MD=no, HAVE_MD=no)
+if test -n "$PKG_CONFIG" && \
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"monodevelop\"") >&5
+  ($PKG_CONFIG --exists --print-errors "monodevelop") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  HAVE_MD=yes
+else
+  HAVE_MD=no
+fi
 
 HAVE_DOC_TOOLS=no
 # Extract the first word of "asciidoc", so it can be a program name with args.
